version: '3.4'

services:
  usersapp.api:
    container_name: usersapp_api
    image: ${DOCKER_REGISTRY-}usersappapi
    build:
      context: .
      dockerfile: UsersApp.API/Dockerfile
    ports:
        - 49152:80
    depends_on:
        - db
        - rabbitmq
  db:
    container_name: usersapp_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "Luan@123456"
        ACCEPT_EULA: "Y"
    ports:
        - "14333:1433"
  rabbitmq:
    container_name: usersapp_rabbitmq
    tty: true
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    expose:
        - 5672
        - 15672
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest


